---
title: "basic_checkplots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basic_checkplots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(checkPlotR)
library(tidyverse)
library(furrr)
```


```{r generate data}
# set up parallel stuff (some tests can take too long otherwise, but could probably get rid of this and lower reps, going to change to 5e3 actually)
#nc <- parallel::detectCores()-1
#plan(strategy = multiprocess, workers = nc)
# generate binomial data, adapted from JD notebook and using the Braker also

set.seed(7082)
numSims <- 5e3
n <- 100
#for binomial
prob <- 0.97

# for normal
mu<-22
sd<-4

## Sim
datNorm<-map_dfr(c(11,15,22,36), function(mymean){
    map_dfr(1:numSims, function(x){
      data.frame(mu=mymean, t(rnorm(n, mean=mymean, sd)))
      })
})

#make output with binom.test

################
# make a big dataframe with different probs and 
to_checkplot<-map_dfr(c(0.5, 0.75, 0.9, 0.97), function(prob){
  dat <- rbinom(numSims, n, prob)
  k<-map_dfr(c("binom.test",  "wald"), function(testv){
   data.frame( multBinom(dat=dat, prob=prob, n=n, testv=testv), testv, prob)
    
  })
  return(k)
})
```

```{r make some plots}
# pdf("figures/wald_and_cp.pdf", height=4.5)
checkPlot(to_checkplot %>% 
            mutate(testv=factor(c("Clopper-Pearson exact","Wald")[as.numeric(as.factor(testv))]
                               , levels=c("Wald","Clopper-Pearson exact")))
                   , facets=8)+
  facet_grid(testv~prob, scales="free_y")+
  labs(x="nominal p-value")+
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,100))+
  theme_classic() + 
  theme(panel.spacing.x = unit(2, "lines"))
# dev.off()

##########
# do it again with normal data, continuous cdf
normtests<- map_dfr(1:length(datNorm$mu), function(samp){
  p<-t.test(datNorm[samp, -1], mu=datNorm[samp,1], alternative="l")$p.value
  ci<-t.test(datNorm[samp, -1], mu=datNorm[samp,1])
  lower<-ci$conf.int[1]
  upper<-ci$conf.int[2]
  est<-ci$estimate
  return(data.frame(p, lower, upper, est, tm=datNorm[samp,1]))
})

######
# some tests to determine how many reps is nice for checkplots

# pdf("figures/norm_22_4.pdf", width=4, height=3)
checkPlot(normtests)+
  theme_classic()
# dev.off()

# png("figures/example_normal_slugplot_22_4.png", width=4, height=3, units="in", res=650)
rangePlot(normtests, title="slugplot: \nCIs for true mean  based on 100 deviates \nfrom norm(22,4)")
dev.off()

# ne<-normtests %>% mutate(fakemu=tm+3)
# rangePlot(ne)+
#   facet_wrap(~tm, scales="free_y")
# 
# rangePlot(ne, target = "fakemu")+
#   facet_wrap(~tm, scales="free_y")





# print(rangePlot(testaccept, orderFun=blob, opacity=0.02))
# print(rangePlot(testchisq, orderFun=blob, opacity=0.02))
# print(rangePlot(testjd, orderFun=blob, opacity=0.02))
# print(rangePlot(testwald, orderFun=blob, opacity=0.002))
```